# Centralized scoring and threshold configurations for SIIP

# Domain Classification Weights
CLASSIFICATION_WEIGHT_SUPERVISED = 0.50
CLASSIFICATION_WEIGHT_SEMANTIC = 0.35
CLASSIFICATION_WEIGHT_TAXONOMY = 0.15

# Confidence thresholds for classification status
CONFIDENCE_THRESHOLD_HIGH = 0.75
CONFIDENCE_THRESHOLD_MEDIUM = 0.50
CONFIDENCE_THRESHOLD_LOW = 0.35
ABSTAIN_THRESHOLD = 0.30

# Similarity threshold defaults
SIMILARITY_DUPLICATE_THRESHOLD = 0.85
SIMILARITY_RELATED_THRESHOLD = 0.65
SIMILARITY_WEAKLY_RELATED_THRESHOLD = 0.30

# University Match weights (must sum up to appropriate scales or 100 max)
MATCH_WEIGHT_DOMAIN = 30.0
MATCH_WEIGHT_EXPERTISE = 25.0
MATCH_WEIGHT_DEPARTMENT = 15.0
MATCH_WEIGHT_PROJECT = 15.0
MATCH_WEIGHT_INFRASTRUCTURE = 10.0
MATCH_WEIGHT_LOCATION = 5.0

# Minimum score to rank a university profile
MIN_MATCH_SCORE = 15.0
