EXPERTISE_TAGS = [
    "Agricultural Engineering",
    "Agronomy",
    "Water Resources",
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Renewable Energy",
    "Thermal Engineering",
    "Environmental Science",
    "Computer Science",
    "Artificial Intelligence",
    "Data Science",
    "Healthcare Technology",
    "Public Health",
    "Biotechnology",
    "Education Technology",
    "Urban Planning",
    "Accessibility Engineering",
    "Social Sciences",
]

EXPERTISE_ALIASES = {
    "crop science": "Agronomy",
    "farming": "Agronomy",
    "soils": "Agronomy",
    "soil science": "Agronomy",
    "post-harvest": "Agricultural Engineering",
    "harvesting tools": "Agricultural Engineering",
    "irrigation systems": "Water Resources",
    "wells": "Water Resources",
    "hydrology": "Water Resources",
    "structural design": "Civil Engineering",
    "road engineering": "Civil Engineering",
    "signal hardware": "Electrical Engineering",
    "power grid": "Electrical Engineering",
    "solar power": "Renewable Energy",
    "wind power": "Renewable Energy",
    "biomass energy": "Renewable Energy",
    "refrigeration": "Thermal Engineering",
    "cooling": "Thermal Engineering",
    "heating": "Thermal Engineering",
    "hvac": "Thermal Engineering",
    "air pollution": "Environmental Science",
    "waste management": "Environmental Science",
    "ecology": "Environmental Science",
    "software": "Computer Science",
    "iot systems": "Computer Science",
    "web portal": "Computer Science",
    "machine learning": "Artificial Intelligence",
    "computer vision": "Artificial Intelligence",
    "deep learning": "Artificial Intelligence",
    "data analytics": "Data Science",
    "statistics": "Data Science",
    "medical devices": "Healthcare Technology",
    "infant incubators": "Healthcare Technology",
    "epidemiology": "Public Health",
    "disease control": "Public Health",
    "vaccine logistics": "Public Health",
    "genetics": "Biotechnology",
    "microbial assays": "Biotechnology",
    "e-learning platforms": "Education Technology",
    "distance learning": "Education Technology",
    "traffic signals": "Urban Planning",
    "transit networks": "Urban Planning",
    "wheelchair ramps": "Accessibility Engineering",
    "screen readers": "Accessibility Engineering",
    "sociology": "Social Sciences",
    "surveys": "Social Sciences",
    "policy analysis": "Social Sciences",
}
